### ISSUE TITLE
Android Chrome support

### ISSUE THREAD

**Issue by smrtak716** [RemiBou/BrowserInterop#92] opened 2020-11-15 12:10 UTC
I can't run geolocation on android chrome (ver. 86.0.4240.198). Dotnet 5.0

var window = await jsRuntime.Window();
var navigator = await window.Navigator();   //error line

Android firefox is OK. Can anyone check it out?

fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '3jXC60Frj0Yr97Nesw5jzNAZn8pqDWoTx22ACo9osDo'.
      Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.Double. Path: $.connection.downlinkMax | LineNumber: 0 | BytePositionInLine: 267.. See InnerException for more details.
       ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Double. Path: $.connection.downlinkMax | LineNumber: 0 | BytePositionInLine: 267.
       ---> System.InvalidOperationException: Cannot get the value of a token type 'String' as a number.
         at System.Text.Json.Utf8JsonReader.TryGetDouble(Double& value)
         at System.Text.Json.Utf8JsonReader.GetDouble()
         at System.Text.Json.Serialization.Converters.DoubleConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
         at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadValueCore[TValue](JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
         at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
         at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
         --- End of inner exception stack trace ---
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at BrowserInterop.Extensions.BrowserInteropJsRuntimeExtension.GetInstanceProperty[T](IJSRuntime jsRuntime, JsRuntimeObjectRef jsObjectRef, String propertyPath, Object serializationSpec)
         at BrowserInterop.Extensions.BrowserInteropJsRuntimeExtension.GetInstancePropertyWrapper[T](IJSRuntime jsRuntime, JsRuntimeObjectRef jsObjectRef, String propertyPath, Object serializationSpec)
         at BrowserInterop.WindowInterop.Navigator()
         at HAWebClient.Pages.Test.GetGeolocation() in C:\projekty\HolyAttendanceMobile\HAWebClient\HAWebClient\Pages\Test.razor:line 32
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by RemiBou** [comment] 2020-11-18 15:50
I'll check it, it might have to do with position precision, the problem is in the connection. downlinkMax , can you get me this value ? (add an alert(navigator.connection. downlinkMax) and load the page)

**Comment by smrtak716** [comment] 2020-11-18 18:24
on mobile is downlinkMax = "infinity"
(testing page: https://klient.adochazka.cz/test )

**Comment by smrtak716** [comment] 2020-11-18 18:50
I confirm that commenting the property DownlinkMax in the WindowNavigatorConnection class solves the problem.

**Comment by RemiBou** [comment] 2020-11-24 22:56
It should be fixed in https://www.nuget.org/packages/BrowserInterop/1.1.2

**Closed by RemiBou** 2020-11-24 22:56 UTC
